### ISSUE TITLE
Failing to get the path

### ISSUE THREAD

**Issue by OwenMelbz** [loganstellway/module-fishpig-bedrock#2]
Hey,

I know you said its not been tested with the other fishpig plugins - however we're trying to use it with it.

Maybe you could help shed some light, then if possible we could submit a PR - however I've only been working with magento 2 for 1 week so might be asking some stupid questions.

---

We're using the taxonomy and custom post type plugin, but its not working as expected - because when the `getPath` method runs within the `Interceptor` class it just returns the root of the project.

This is because `$pluginInfo = $this->pluginList->getNext('LoganStellway\FishPigBedrock\Model\App', 'getPath');` returns `null`

Thus it calls `parent::getPath()` which falls back to the original fishpig plugin and cant read the proper fishpig path.

I've no idea what the pluginList->getNext or the ___callPlugins thing is meant to do.

However would you be able to help suggest why it might not be returning what is expected? Happily share the plugin code with you if need it to debug yourself.

Many thanks

**Comment by OwenMelbz** [comment]
Okay, i realised this is because of what I changed like an idiot.

Fix is https://github.com/loganstellway/module-fishpig-bedrock/pull/3

**Comment by loganstellway** [comment]
Hey @OwenMelbz,

I remembered doing something weird to make the module work well with my [module-fishpig-root](https://github.com/loganstellway/module-fishpig-root) module. I'll need to review the functionality between the both of them to make sure everything works well - I should be able to review everything more thoroughly over the next month. 

Thanks! 👍
